all:
	gcc -Wall 43_sort-binary-file.c -o 43.o

clean:
	rm *.o

43:
	gcc -Wall 43_sort-binary-file.c -o 43.o

44:
	gcc -Wall 44_numbers_in_interval.c -o 44.o

45:
	gcc -Wall 45_sort_numbers.c -o 45.o

46:
	gcc -Wall 46_dat-idx.c -o 46.o

47:
	gcc -Wall 47_differences.c -o 47.o

48:
	gcc -Wall 48_cat.c -o 48.o
